### PR TITLE
added above-post-stream and topic-above-suggested

### PR DESCRIPTION
**Pull request by snjqi188**
@jocranford - your comments appreciated on this PR, let's discuss this at our hangouts catch up this week.
Background: We are extending the master branch to create 2 additional locations for ad slots within discourse.
*This commit has the code that add 2 more locations for ads*.  They utilise plugin outlets already created within discourse: See [what are plugin outlets](https://meta.discourse.org/t/beginners-guide-to-creating-discourse-plugins-part-2-plugin-outlets/31001) and [plugin outlet locations](https://meta.discourse.org/t/plugin-outlet-locations/29589).
It's also been tested locally.

locations 1 and 2: topic-above-post-stream and topic-above-suggested
screen shot 2015-07-20 at 2 41 16 pm

location 3: discovery-list-container-top
screen shot 2015-07-20 at 2 41 25 pm

### CODE REVIEW

**Comment by eviltrout** [comment]
:+1:

**Comment by jocranford** [comment]
My only comment on this @snjqi188 is whether there's an alternative way to store the "magic" numbers for the ad size? You refer to them twice in the js plus in the yml (you could use tokens and replace them). That said I understand ads are pretty standard sizes and these are unlikely to change so if you decide it's better to leave as is, that works for me :) 

:+1:

**Comment by snjqi188** [comment]
@jocranford thanks for the feedback, will work on this issue tomorrow.

**Comment by snjqi188** [comment]
@jocranford heya jo, is there any site i could learn more on how to implement tokens in js files? :-) it's a rather new concept to me..

**Comment by jocranford** [comment]
@snjqi188 I can't see whereabouts this particular piece of text in the yml is being used in the code in this repo? (```dfp_show_topic_above_post_stream``` or ```dfp_show_topic_above_suggested```) - can you point me to it?

This is an example of using tokens, or variables, in yml files in Rails: 
http://stackoverflow.com/questions/13055753/passing-variables-inside-rails-internationalization-yml-file

Within the javascript file, you could define the height and width as constants: 
```
const height=200; 
const width=350; 
``` 
or something similar. 

I usually try and create variables to represent particular constant values like numbers or strings, so that it's clearer in the code what they mean, and so that if you need to change them later, they're just in one place. 

Please feel free to say if you decide to leave as it is, just a suggestion :)

**Comment by snjqi188** [comment]
@jocranford hey jo, we removed it because Robin suggested that users could reduce one step by simply putting their code in (makes things simpler) to show the ad. Instead of clicking a button to enable the show, thus we removed `dfp_show_topic_above_post_stream` and `dfp_show_topic_above_suggested` 

cool, will experiment with tokens!

**Pull request merged**
